### ISSUE TITLE
トップページのnewsのサマリでstrikeタグを使っても無視される

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matsuerb-nanoc#178]
リンクが無視されるなどはかまわないとしても、できればstrikeは残って欲しいところ。
8/8 の訂正のお知らせでは直接 github.io の方を修正して対応した。

**Comment by sada** [comment]
strikeタグは非推奨になったので、sタグに変更しました。

https://developer.mozilla.org/ja/docs/Web/HTML/Element/strike

また、取り消し線が表示される状態ですので閉じます。
