### ISSUE TITLE
scheduleページのUstreamのリンクをYoutubeに張り替える

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matsuerb-nanoc#190]
Ustreamの動画が削除されるため。10/10までに対応の予定。

**Comment by sada** [comment]
Ustreamはサービス終了しているため、Matsue.rbの公式サイト内のUstreamの動画のリンクを削除します。
動画がアップロードし直された場合、そちらにリンクを変更することにします。

**Comment by sada** [comment]
Ustreamのリンクの削除を行い、過去の松江Ruby会議のYouTubeの動画へのリンクを追加したので閉じます。

https://github.com/matsuerb/matsuerb-nanoc/pull/910
