### ISSUE TITLE
Matsue.rbのデザイン変更（リニューアル）をする。

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matsuerb-nanoc#347]
@KatoAtsue さん

とりあえずコンテンツ（サイト構成）はそのままでデザイン作成をお願いします！

**Comment by KatoAtsue** [comment]
@yoshiokaCB さん
承知しました。
次回以降のMatsue.rbで、画面の確認や修正指示をしていただきながら、作成したいと思いますのでよろしくお願いします。

**Comment by KatoAtsue** [comment]
リニューアルのためのファイル追加と変更について以下を予定しております。
[変更ファイル：4、追加ファイル：40(画像はfavicon等少し追加する予定です。)]
5月の定例会以降でデザイン・構成共に了解をいただいてから作業したいと思います。
修正が必要な箇所等ありましたらお知らせください。
よろしくお願いします。
 .
│── content
│   │── index.html (変更)
│   └── schedule.html (変更：スマホ対応のためtableのクラス名と「|:---:|」を「|-----|」に変更)
│── layouts
│   │── _head.html (変更)
│   └── default.html (変更)
└── static
    │── css
    │   │── sitecontents.css (追加：サイト全体用)
    │   └── siteindex.css (追加：トップページとナビゲーション用)
    │── images
    │   │── bn (フォルダ追加：バナーとアイコン、ファイル数：4)
    │   └── member (フォルダ追加：メンバーのイラスト、ファイル数：31)
    └── js
        └── grid (フォルダ追加：メンバー表示と段組のためのjavascript、ファイル数：3)

**Comment by yoshiokaCB** [comment]
@KatoAtsue さん
了解です！ありがとうございます！！
特に問題はないと思いますが、また定例会の時に相談させてください。
（色々と忘れちゃってるので、定例会までに構成を思い出しときます。）

**Comment by KatoAtsue** [comment]
@yoshiokaCB さん
どうもありがとうございます。
よろしくお願いします。

**Comment by sho-h** [comment]
@KatoAtsue さんお疲れさまです！先にPull Requestにしていただいて見ておけたらと思うのですが、不安とかあれば当日一緒に作業させてください！

**Comment by KatoAtsue** [comment]
@sho-h さん
どうもありがとうございます。
定例会で作業したいと思いますのでよろしくお願いします。

**Comment by sho-h** [comment]
はいー。

**Comment by KatoAtsue** [comment]
@sho-h さん
@yoshiokaCB さん
ファイルを修正して「git push origin new_design」しました。
何か問題がありましたらご指摘ください。
よろしくお願いします。

**Comment by sho-h** [comment]
@KatoAtsue さん、ありがとうございますー。後で見てみます！

**Comment by yoshiokaCB** [comment]
@KatoAtsue さん
ありがとうございます！
確認してみます。

**Comment by yoshiokaCB** [comment]
@KatoAtsue さん
確認しました！
ヘッダーに赤が入って引き締まりましたね！！
これで特に問題はないと思います。

**Comment by sho-h** [comment]
僕もデザインは特になくなりました！追加で気付いたのですが、ロゴの右側にマウスが来た時にクリックできるのが若干気になります(こないだ気付けなくてすみません...)。以下のような感じでリンクをmatsuerb_layer.pngまで含めるか、含めないかだけ相談させてください。

```
diff --git a/layouts/default.html b/layouts/default.html
index 39525cd..8384d0c 100644
--- a/layouts/default.html
+++ b/layouts/default.html
@@ -7,9 +7,9 @@

 <ul class="menu">
 <% if @item.identifier.size == 1 %>
-<li data-ag-x="3"><h1><a href="/"><img src="/images/bn/matsuerb_layer.png" alt="*"/><img src="/imag
es/bn/matsuerb.png" alt="matsue.rb 松江Ruby"/></a></h1></li>
+<li data-ag-x="3"><h1><img src="/images/bn/matsuerb_layer.png" alt="*"/><a href="/"><img src="/imag
es/bn/matsuerb.png" alt="matsue.rb 松江Ruby"/></a></h1></li>
 <% else %>
-<li data-ag-x="3"><a href="/"><img src="/images/bn/matsuerb_layer.png" alt="*"/><img src="/images/b
n/matsuerb.png" alt="matsue.rb 松江Ruby"/></a></li>
+<li data-ag-x="3"><img src="/images/bn/matsuerb_layer.png" alt="*"/><a href="/"><img src="/images/b
n/matsuerb.png" alt="matsue.rb 松江Ruby"/></a></li>
 <% end %>
 <li><a href="/news/"><div class="toc">お知らせ</div></a></li>
 <li><a href="/about_us/"><div class="toc">松江Rubyとは</div></a></li>
```

この話は1回マージして別の修正としてもいいかもしれませんね。

**Comment by KatoAtsue** [comment]
@sho-h さん
@yoshiokaCB さん
どうもありがとうございます。
コードを確認してみます。

**Comment by KatoAtsue** [comment]
修正してみました。

**Comment by sho-h** [comment]
おぉ、ありがとうございます！僕も特になくなりましたので夜にでもマージしようかと思います。

**Comment by sho-h** [comment]
マージしました。反映はもう少し時間が取れそうな時にさせてください。遅くとも今月の定例会には作業します。

**Comment by KatoAtsue** [comment]
どうもありがとうございます。
よろしくお願いします。

**Comment by KatoAtsue** [comment]
後になってから申し訳ありません。
メンバーのイラストを１枚追加させていただきたいと思いますのでよろしくお願いします。
リニューアル後でもいつでも構いません。

**Comment by sho-h** [comment]
反映したのでcloseします。
