### ISSUE TITLE
twitterのタイムライン表示でエラーが出ているのを修正

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matsuerb-nanoc#580]
以下がでてるけど関係があるかは不明。

```
[Error] Profile timeline for screen_name: search not found
```

**Comment by sada** [comment]
確認したところ、Twitterの検索結果のタイムラインはサポートされなくなったようです。

https://twittercommunity.com/t/replacing-deprecated-timeline-search-widget/103627

現在の見た目のTwitterの表示をしたい場合、検索APIで取得した情報をタイムラインのように表示するように作成する必要があるようでした。
私はMatsue.rbのTwitterアカウントにログインできないので、橋本さんにTwitter APIの登録の作業をお願いしました。

**Comment by sada** [comment]
Twitterのタイムラインは公式サイトから削除することになりました。

**Comment by sada** [comment]
#669 のPRで対応しましたので閉じます。
